language: generic

before_script:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_arm.zip -O bin/terraform.zip
  - unzip -o bin/terraform.zip
  - rm bin/terraform.zip

script:
  - ls -la
  - ls -la bin
  - ./bin/terraform init terraformFiles