language: generic

before_script:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_arm.zip -O terraform.zip
  - unzip terraform.zip -o

script:
  - ls -la
  - terraform init terraform