language: generic

before_script:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_arm.zip -O terraform_compressed.zip
  - unzip terraform_compressed.zip

script:
  - ls -la
  - terraform init terraform