language: generic

env:
  global:
    - secure: KJiJNSPc2gyPFKKmPtrMFPf5J7gOqS8ievFEEq4KY4XvSLnusrQA1FMINA+DZGsLi2ptPTF3a6ZqAV4J0xXzhy4YhdXiSmTUaKvZY/kdaVII+pYjeEkzQ9Z6c3HE4ymKopgtB7HfNecUKpPoXGjnc3UUzOdePDnHC5nfY8HppoMavy4JXwMHHylbiNlMokCIj6g0HPpBt0ZxNZQtmz9Vd0gF0TySc5JVKHfMCp+wt47EXi/Y690cQ+/Nn6jOJhxTQBRH6edsL9nCruqNd9Dq0sDMesJaUY3+8BdggPxdf7zx8Vq79/1SPAeG0bk2LcPY1ZXidMMWABQ6d26uRU8bS/Z83EhxisQ4zz3kTVnCtdtil962vx3F95Mat34G9UxBjycmR3eCjMWsbSor04SvNAUOHKUNJP2HTzTere+asNdzRNAcHXf6z5+BH1wV4NOZ+fv6lONZ+axoPy+61bcmo+QwbCdfa+zco0L4Csyf5K8y+mjZ1cjebyZ12U5xcXZyNe0z8Bgs4WFUkOulvyay02kJFn4ROENLUAsxGZw8pEpwuBKymLum2ONGtefRKhO1baYj1K7XYEnSxkd2n+2Sv/W+NTpT4NIVZY2AFGVG3uCcTgVEvVN8OkfXrvtCkUyugWKQ9wnpN0VcxXdQL3z41/JhmCiGjm2kEe8AqDb+Pxg=
    - secure: UxauE5DRKL+4MCvpzLq8tPZ6C+l5XsRig5PDU7V8D5wWKOLnOcdy4kqaRSx2RNbKCgaeS+0f1GRT94L+m0B2/JH69LknPbB+qx4H7ODV23U823kiC38XHUOdUCYRQRn6ocXGGYNU9I/Kbdt9zMdpVRs0cLIlAtm7x4KgFqTxQPgUMLw/IjiAScUoW4xnBnSDhoa+joOmHLYII9Otctu3NAenCSLqPTPzpam8j6Vwb5NYaC2LZ9Q7yxBfA/eJvHjrc1xEc4sf7yIAvyagP80odJa+GUHrHsxGVDtjzad9MB2a7zEKyqOThyn68pTPsRVuM4f4pKzgsXDbeWpk9Y/0mxvX1QdFscwUTyPa6eHp/sa5AffEzzAsOzRv2X69sS2vrih3eYABiGQBw0bVD8+8vsTeSWFXaDyuP1y+12R9Cg3Z9XrThH6XRNR7TO+qMSN3yOTaMLoMkIhCMI/VHdvmdJGcT4vXjUfYs0rjF3upFrSSS10i4fYhkiPgyWkodzjWIH4lGJXlA6spYv/f7ajOjdR033hq7+lIAwFzISsQ51PT34hQ5SRmElqrpuDCNJWv3yysDlEUAsIRST6jfWzwQTHIDSMlTORW/vnejrywuCi4xmGia0OV7B3CAdQii49edmeD2twiG2W3B37DTRwnBR7Z5g5gw1b6qBzQq5ZadY8=
    - secure: QWVOyqkDBBzvufsHePJ0Y+rSX+tiMS12ViIJXlGYvTk0Z8Q2bLBSEJj8ejNfzZwE7vePJqChwY2biArKhCChDHZvE5FMo2wD80YrdstYVJNbmL41GBHKWH65YCCAjcW9dgKy8MP2xjRRqNeOC3YTlHjunrEBlSE8QHOMtLqtYUyET5dGDTyCC9mLPF4lkCTeRH6cD9zAW1Tdtc9ZRHFHYn7eV53fKhTTO2f2l8GmHnc5Vzx6Yfoel4NYoToNho7Zhg6Jt3C/Nd3nwShq2VagMgiiiTAVYzE9I9odT5Ozqex/KHgWFGpbRU2oIRIcvb2mVHcdX9VUDAKs+3ToxdHVbBun0sAMOfBoySNE4hzVFgdw4gy5cJXrntDriY46h+AhFuVMp2xjMnmI7xiFCGAzJLhpmLNL/CHCxK5/gPIABoSyei4jX3afyPA59Mfz3pFV7EfUnQX3wh8/8WxWCswg0JGJWD/AFgG3AgUxEmVnFK6vE4QTHegWpH94gtdvFLDQ4vuJDO/KFjSpR3kBXlsUV7tPYebaTNBPWnCA69uJuxgpo0phPuWmrK0JpVltZu/iTS23SxTFUZ9i5TY9e4EalpXg9FWulEy9txAO6BEV/k0fy7qeWa8z7tO2ImiYMBaoj3OhsIDj+eexM44YOV62jp4x1Cde2gvioo5nl36Cz3Q=
    - secure: d9egEe61Kspm4KPj2zPAz5LQtzAAffcnvrFN6zOoYBz4IymQh4Kj9QmV/uZ4XGTRDz8UT07k2RP2PCtffoE9tujjuYm4CiSbIIp40b/s3SkvSai6tm0opJMnEX4aZcWa6wxHE80eThSmr3hpyk0MYB9BBrbn9Na+ADXmTpi9Xwk/yOPmyI3+84DF6fl6+UBNzSqas+sJLgyW/EHhUfZh8JykVi3RIGxQaKnNyZrg/1DDAP88pypvsIASsunFW4PUqbonS3mOKXLfmKtfY+sFGXV2nKlDYXq6CY1g9aKOHGRM83GMf7HC4cfdshYkZSFuVZW0JU+MzOMUGl5MoUEJTjjw4+drjRDJMzMvUbOd0k5Lkw6WV1hh2/iEulIc6MwjgsT1xZgyxlfse+T9HzBOSpUv+1jo4aJUjKyp12ywqiWhq9I2kunYbu+ET8Q8LtXgHf5XtUAHBtefiIrSdx7OxLvI702q6lktHtRridMv3Ock75i3E1sUnOKhlAeN+AhQT34HDUMCiQhs4iJTE0ivAGHunNmiOxweRcmRnN63Cru+aAyjIK0YBHXXlW2PPbi76W8w92thXnfd+PUC0ynyqtHb4ku85Oqi0/xSEkhTuDJNyk2c/lwQnbRASNiO2qy/7gDES5b/p/D38s7OzgXvAYbgUATbnbsXxTUsxRbKUVo=

before_script:
  - mkdir bin
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    -O bin/terraform.zip
  - unzip bin/terraform.zip -d bin
  - rm bin/terraform.zip
  - "./bin/terraform init terraform"
  - pip install awscli --upgrade --user

jobs:
  include:
    - stage: initialize
      name: Initialize S3 buckets for lambda upload
      script:
        - "./scripts/initializeS3Bucket.sh"
    - stage: upload
      name: Upload changed Lambda Functions
      script:
        - echo 'Uploading lambda functions'
    - stage: apply
      name: Applying changes
      script:
        - echo 'Applying changes'
    - stage: delete
      name: Delete all created resources
      script:
        - "./bin/terraform destroy -auto-approve terraform"
