language: generic

env:
  global:
    # TF_VAR_access_key
    - secure: KJiJNSPc2gyPFKKmPtrMFPf5J7gOqS8ievFEEq4KY4XvSLnusrQA1FMINA+DZGsLi2ptPTF3a6ZqAV4J0xXzhy4YhdXiSmTUaKvZY/kdaVII+pYjeEkzQ9Z6c3HE4ymKopgtB7HfNecUKpPoXGjnc3UUzOdePDnHC5nfY8HppoMavy4JXwMHHylbiNlMokCIj6g0HPpBt0ZxNZQtmz9Vd0gF0TySc5JVKHfMCp+wt47EXi/Y690cQ+/Nn6jOJhxTQBRH6edsL9nCruqNd9Dq0sDMesJaUY3+8BdggPxdf7zx8Vq79/1SPAeG0bk2LcPY1ZXidMMWABQ6d26uRU8bS/Z83EhxisQ4zz3kTVnCtdtil962vx3F95Mat34G9UxBjycmR3eCjMWsbSor04SvNAUOHKUNJP2HTzTere+asNdzRNAcHXf6z5+BH1wV4NOZ+fv6lONZ+axoPy+61bcmo+QwbCdfa+zco0L4Csyf5K8y+mjZ1cjebyZ12U5xcXZyNe0z8Bgs4WFUkOulvyay02kJFn4ROENLUAsxGZw8pEpwuBKymLum2ONGtefRKhO1baYj1K7XYEnSxkd2n+2Sv/W+NTpT4NIVZY2AFGVG3uCcTgVEvVN8OkfXrvtCkUyugWKQ9wnpN0VcxXdQL3z41/JhmCiGjm2kEe8AqDb+Pxg=
    # TF_VAR_secret_key
    - secure: UxauE5DRKL+4MCvpzLq8tPZ6C+l5XsRig5PDU7V8D5wWKOLnOcdy4kqaRSx2RNbKCgaeS+0f1GRT94L+m0B2/JH69LknPbB+qx4H7ODV23U823kiC38XHUOdUCYRQRn6ocXGGYNU9I/Kbdt9zMdpVRs0cLIlAtm7x4KgFqTxQPgUMLw/IjiAScUoW4xnBnSDhoa+joOmHLYII9Otctu3NAenCSLqPTPzpam8j6Vwb5NYaC2LZ9Q7yxBfA/eJvHjrc1xEc4sf7yIAvyagP80odJa+GUHrHsxGVDtjzad9MB2a7zEKyqOThyn68pTPsRVuM4f4pKzgsXDbeWpk9Y/0mxvX1QdFscwUTyPa6eHp/sa5AffEzzAsOzRv2X69sS2vrih3eYABiGQBw0bVD8+8vsTeSWFXaDyuP1y+12R9Cg3Z9XrThH6XRNR7TO+qMSN3yOTaMLoMkIhCMI/VHdvmdJGcT4vXjUfYs0rjF3upFrSSS10i4fYhkiPgyWkodzjWIH4lGJXlA6spYv/f7ajOjdR033hq7+lIAwFzISsQ51PT34hQ5SRmElqrpuDCNJWv3yysDlEUAsIRST6jfWzwQTHIDSMlTORW/vnejrywuCi4xmGia0OV7B3CAdQii49edmeD2twiG2W3B37DTRwnBR7Z5g5gw1b6qBzQq5ZadY8=

before_script:
  - mkdir bin
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
    -O bin/terraform.zip
  - unzip bin/terraform.zip -d bin
  - rm bin/terraform.zip
  - "./bin/terraform init terraformFiles"

script:
  - "./bin/terraform plan terraformFiles"
  - "./bin/terraform apply terraformFiles -auto-approve"
